#!/usr/bin/env python3
"""Procedural placeholder textures for Crazy Alloy: Revival (stage 1).

All textures here are ORIGINAL and PROVISIONAL: they are generated by this script (no vanilla or
original-mod pixels are copied) so the mod is playable and visually consistent until hand-drawn art
replaces them. Palette and 16x16 resolution follow vanilla conventions.
Run: python3 tools/gen_textures.py   (requires Pillow)
"""
import math, os, random
from PIL import Image, ImageDraw

NS = "crazyalloy_revival"
T = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "src", "main", "resources", "assets", NS, "textures")
R = random.Random(20261001)

def hexc(h, a=255):
    h = h.lstrip("#")
    return (int(h[0:2], 16), int(h[2:4], 16), int(h[4:6], 16), a)

def shade(c, f):
    return tuple(max(0, min(255, int(v * f))) for v in c[:3]) + (c[3],)

def save(img, rel):
    p = os.path.join(T, rel)
    os.makedirs(os.path.dirname(p), exist_ok=True)
    img.save(p)

def noise(size, palette, weights=None):
    img = Image.new("RGBA", (size, size))
    px = img.load()
    for y in range(size):
        for x in range(size):
            px[x, y] = R.choices(palette, weights=weights)[0]
    return img

# ------------------------------------------------------------------ palettes
CHOC = [hexc("5a3420"), hexc("6b3e26"), hexc("7a472c"), hexc("4e2c1a")]
CHOC_LIGHT = [hexc("8a5634"), hexc("7a472c"), hexc("94603b")]
FROST = [hexc("ffd1e8"), hexc("ffc0df"), hexc("ffe3f1"), hexc("f7b2d6")]
STONE = [hexc("7d7d7d"), hexc("747474"), hexc("858585"), hexc("6c6c6c"), hexc("8c8c8c")]
DEEP = [hexc("4d4d55"), hexc("45454c"), hexc("55555d"), hexc("3d3d44")]
TOUR = [hexc("e0487f"), hexc("f06a9a"), hexc("b8305f"), hexc("ff9cc0")]
WOOD = [hexc("f3e6d4"), hexc("eadac4"), hexc("fbf1e3")]
STRIPE = hexc("e8507f")

def blocks():
    soil = noise(16, CHOC)
    save(soil, "block/chocolate_soil.png")

    top = noise(16, FROST)
    d = top.load()
    for _ in range(10):  # sprinkles
        x, y = R.randrange(16), R.randrange(16)
        d[x, y] = R.choice([hexc("ff4f7b"), hexc("6ad1ff"), hexc("ffe35a"), hexc("8be27a"), hexc("ffffff")])
    save(top, "block/chocolate_grass_block_top.png")

    side = noise(16, CHOC)
    s = side.load()
    for x in range(16):
        drip = 3 + (2 if R.random() < 0.35 else 0) + (1 if R.random() < 0.3 else 0)
        for y in range(drip):
            s[x, y] = R.choice(FROST)
        s[x, drip] = shade(FROST[0], 0.85)
    save(side, "block/chocolate_grass_block_side.png")

    choc = noise(16, CHOC_LIGHT)
    c = choc.load()
    for i in range(16):  # bar segment grooves
        for g in (0, 8):
            c[g, i] = shade(CHOC_LIGHT[0], 0.7)
            c[i, g] = shade(CHOC_LIGHT[0], 0.7)
            c[(g + 7) % 16, i] = shade(CHOC_LIGHT[2], 1.15)
            c[i, (g + 7) % 16] = shade(CHOC_LIGHT[2], 1.15)
    save(choc, "block/chocolate_block.png")

    bricks = noise(16, CHOC)
    b = bricks.load()
    mortar = hexc("3a2013")
    for y in range(16):
        for x in range(16):
            row = y // 4
            off = 4 if row % 2 else 0
            if y % 4 == 3 or (x + off) % 8 == 7:
                b[x, y] = mortar
            elif y % 4 == 0:
                b[x, y] = shade(b[x, y], 1.2)
    save(bricks, "block/chocolate_bricks.png")

    chis = noise(16, CHOC)
    ch = chis.load()
    for i in range(16):
        for j in (0, 15):
            ch[i, j] = mortar
            ch[j, i] = mortar
    for i in range(3, 13):
        for j in (3, 12):
            ch[i, j] = shade(CHOC[2], 1.3)
            ch[j, i] = shade(CHOC[2], 1.3)
    for (x, y) in [(7, 7), (8, 7), (7, 8), (8, 8), (6, 7), (9, 8), (7, 6), (8, 9)]:
        ch[x, y] = FROST[0]
    save(chis, "block/chiseled_chocolate_bricks.png")

    log = noise(16, WOOD)
    l = log.load()
    for y in range(16):  # candy-cane spiral stripes
        for x in range(16):
            if (x + y) % 8 < 3:
                l[x, y] = shade(STRIPE, 0.95 + R.random() * 0.1)
    save(log, "block/sweetwood_log.png")
    lt = noise(16, WOOD)
    ltp = lt.load()
    for y in range(16):
        for x in range(16):
            r = math.hypot(x - 7.5, y - 7.5)
            if r > 6.8:
                ltp[x, y] = shade(STRIPE, 1.0)
            elif int(r) % 3 == 0:
                ltp[x, y] = shade(WOOD[1], 0.88)
    save(lt, "block/sweetwood_log_top.png")

    planks = noise(16, WOOD)
    p = planks.load()
    for y in range(16):
        for x in range(16):
            if y % 4 == 3:
                p[x, y] = hexc("d6bfa3")
            elif (x + (y // 4) * 5) % 16 == 0:
                p[x, y] = hexc("d6bfa3")
            elif y % 4 == 0:
                p[x, y] = shade(p[x, y], 1.03)
    save(planks, "block/sweetwood_planks.png")

    leaves = Image.new("RGBA", (16, 16), (0, 0, 0, 0))
    lv = leaves.load()
    for y in range(16):
        for x in range(16):
            if R.random() < 0.82:
                lv[x, y] = R.choice([hexc("ffb3dd"), hexc("ff9fd2"), hexc("ffc9e8"), hexc("f58cc4"), hexc("ffd9ef")])
    save(leaves, "block/cotton_candy_leaves.png")

    sap = Image.new("RGBA", (16, 16), (0, 0, 0, 0))
    sd = ImageDraw.Draw(sap)
    sd.line([(8, 15), (8, 8)], fill=hexc("f3e6d4"))
    sd.point([(8, 13), (8, 10)], fill=STRIPE)
    sd.ellipse([4, 2, 12, 9], fill=hexc("ffb3dd"))
    sd.ellipse([5, 3, 9, 6], fill=hexc("ffd9ef"))
    sd.point([(10, 7), (6, 8)], fill=hexc("f58cc4"))
    save(sap, "block/sweetwood_sapling.png")

    flower = Image.new("RGBA", (16, 16), (0, 0, 0, 0))
    fd = ImageDraw.Draw(flower)
    fd.line([(8, 15), (8, 8)], fill=hexc("f5f5f5"))
    fd.line([(8, 12), (10, 10)], fill=hexc("5fbf4f"))
    fd.line([(8, 13), (6, 11)], fill=hexc("5fbf4f"))
    fd.ellipse([4, 1, 12, 9], fill=hexc("ff4f7b"))
    for a in range(0, 360, 45):  # swirl
        x = 8 + math.cos(math.radians(a)) * (a / 120)
        y = 5 + math.sin(math.radians(a)) * (a / 120)
        flower.putpixel((int(round(x)), int(round(y))), hexc("fff2f6"))
    save(flower, "block/lollipop_flower.png")

    def ore(base, name):
        img = noise(16, base)
        o = img.load()
        for (cx, cy) in [(4, 4), (11, 5), (6, 11), (12, 12)]:
            for dx, dy in [(0, 0), (1, 0), (0, 1), (-1, 0), (0, -1), (1, 1)]:
                if R.random() < 0.9:
                    o[(cx + dx) % 16, (cy + dy) % 16] = R.choice(TOUR)
            o[cx, cy] = hexc("ffd0e2")
        save(img, f"block/{name}.png")
    ore(STONE, "tourmaline_ore")
    ore(DEEP, "deepslate_tourmaline_ore")

    tb = noise(16, TOUR, [3, 3, 2, 1])
    t = tb.load()
    for i in range(16):
        t[i, 0] = hexc("ffb7d1"); t[0, i] = hexc("ffb7d1")
        t[i, 15] = hexc("8f2449"); t[15, i] = hexc("8f2449")
    for i in range(2, 14):
        t[i, i] = hexc("ffc9dc")
    save(tb, "block/tourmaline_block.png")

    def metal():
        img = noise(16, [hexc("6b6f75"), hexc("62666c"), hexc("72767c")])
        m = img.load()
        for i in range(16):
            m[i, 0] = m[0, i] = hexc("8a8e94")
            m[i, 15] = m[15, i] = hexc("4a4d52")
        for (x, y) in [(2, 2), (13, 2), (2, 13), (13, 13)]:
            m[x, y] = hexc("b0b4ba")
        return img
    fs = metal()
    d = ImageDraw.Draw(fs)
    d.rectangle([3, 5, 12, 10], fill=CHOC[1])
    d.line([(3, 7), (12, 7)], fill=CHOC[3])
    save(fs, "block/chocolate_factory_side.png")
    ft = metal()
    d = ImageDraw.Draw(ft)
    d.rectangle([5, 5, 10, 10], fill=hexc("3a3d41"))
    d.rectangle([6, 6, 9, 9], fill=hexc("26282b"))
    save(ft, "block/chocolate_factory_top.png")
    for lit in (False, True):
        ff = metal()
        d = ImageDraw.Draw(ff)
        d.rectangle([3, 3, 12, 6], fill=hexc("26282b"))
        d.line([(3, 4), (12, 4)], fill=CHOC[2])
        d.rectangle([4, 9, 11, 13], fill=hexc("26282b"))
        if lit:
            for x in range(5, 11):
                ff.putpixel((x, 12), hexc("ffb347")); ff.putpixel((x, 11), hexc("ff7a2a") if x % 2 else hexc("ffd166"))
            ff.putpixel((7, 10), hexc("ffd166")); ff.putpixel((8, 10), hexc("ff7a2a"))
        else:
            for x in range(5, 11):
                ff.putpixel((x, 12), hexc("3a3d41"))
        save(ff, f"block/chocolate_factory_front{'_on' if lit else ''}.png")

# ------------------------------------------------------------------ items
def blank():
    return Image.new("RGBA", (16, 16), (0, 0, 0, 0))

def items():
    g = blank(); d = ImageDraw.Draw(g)
    d.polygon([(8, 2), (13, 6), (13, 10), (8, 14), (3, 10), (3, 6)], fill=TOUR[0], outline=hexc("8f2449"))
    d.polygon([(8, 3), (11, 6), (8, 8), (5, 6)], fill=TOUR[3])
    d.line([(8, 8), (8, 13)], fill=TOUR[2])
    save(g, "item/tourmaline.png")

    p = blank(); d = ImageDraw.Draw(p)
    d.ellipse([3, 7, 13, 14], fill=CHOC[1], outline=CHOC[3])
    d.ellipse([5, 5, 11, 11], fill=CHOC_LIGHT[0])
    for _ in range(6):
        p.putpixel((R.randint(5, 11), R.randint(6, 12)), CHOC_LIGHT[2])
    save(p, "item/cocoa_powder.png")

    t = blank(); d = ImageDraw.Draw(t)
    for i in range(10):
        x, y = 3 + i, 12 - i
        col = STRIPE if (i // 2) % 2 == 0 else hexc("fff4f8")
        d.rectangle([x, y - 1, x + 1, y], fill=col)
    save(t, "item/candy_tube.png")

    def bar(name, base, top):
        b = blank(); d = ImageDraw.Draw(b)
        d.rectangle([2, 4, 13, 12], fill=base, outline=shade(base, 0.6))
        for x in (6, 10):
            d.line([(x, 5), (x, 11)], fill=shade(base, 0.75))
        d.line([(3, 8), (12, 8)], fill=shade(base, 0.75))
        d.rectangle([2, 10, 13, 13], fill=top)
        d.line([(2, 10), (13, 10)], fill=shade(top, 1.2))
        save(b, f"item/{name}.png")
    bar("chocolate_bar", CHOC_LIGHT[0], hexc("c0392b"))
    bar("milk_chocolate", hexc("b07a4f"), hexc("2f7fd8"))

    lp = blank(); d = ImageDraw.Draw(lp)
    d.line([(8, 9), (8, 15)], fill=hexc("f5f5f5"))
    d.ellipse([3, 1, 13, 11], fill=hexc("ff4f7b"), outline=hexc("b82a50"))
    for a in range(0, 540, 30):
        r = a / 140
        x = 8 + math.cos(math.radians(a)) * r
        y = 6 + math.sin(math.radians(a)) * r
        lp.putpixel((int(round(x)), int(round(y))), hexc("fff2f6"))
    save(lp, "item/lollipop.png")

    cc = blank(); d = ImageDraw.Draw(cc)
    d.line([(8, 10), (8, 15)], fill=hexc("f3e6d4"))
    d.ellipse([2, 1, 14, 11], fill=hexc("ffb3dd"))
    d.ellipse([4, 2, 10, 7], fill=hexc("ffd9ef"))
    d.point([(11, 8), (5, 9), (12, 4)], fill=hexc("f58cc4"))
    save(cc, "item/cotton_candy.png")

    gr = blank(); d = ImageDraw.Draw(gr)
    d.line([(8, 1), (8, 4)], fill=hexc("6b8e23"))
    d.polygon([(8, 2), (12, 1), (11, 3)], fill=hexc("5fbf4f"))
    for (x, y) in [(5, 5), (9, 5), (7, 8), (11, 8), (5, 9), (9, 11), (7, 12)]:
        d.ellipse([x - 2, y - 2, x + 2, y + 2], fill=hexc("7b3fa0"), outline=hexc("4b2263"))
        gr.putpixel((x - 1, y - 1), hexc("b07ad1"))
    save(gr, "item/grape.png")

    handle = hexc("f3e6d4"); hstripe = STRIPE
    def tool(name, head_pts, extra=None):
        im = blank(); d = ImageDraw.Draw(im)
        for i in range(9):  # diagonal candy-cane handle bottom-left to center
            x, y = 2 + i, 13 - i
            im.putpixel((x, y), hstripe if i % 3 == 0 else handle)
        d.polygon(head_pts, fill=TOUR[0], outline=hexc("8f2449"))
        if extra:
            extra(d)
        save(im, f"item/{name}.png")
    sw = blank(); d = ImageDraw.Draw(sw)
    for i in range(10):
        x, y = 5 + i, 10 - i
        d.rectangle([x - 1, y - 1, x, y], fill=TOUR[0])
        sw.putpixel((x, y - 1), TOUR[3])
    d.line([(2, 10), (6, 14)], fill=hexc("8f2449"))
    for i in range(3):
        sw.putpixel((2 + i, 13 - i), hstripe if i == 0 else handle)
    sw.putpixel((1, 14), hstripe)
    save(sw, "item/tourmaline_sword.png")
    tool("tourmaline_pickaxe", [(3, 4), (8, 1), (13, 2), (14, 7), (12, 5), (8, 4), (5, 6)])
    tool("tourmaline_axe", [(8, 2), (12, 1), (14, 4), (13, 8), (10, 7), (9, 5)])
    tool("tourmaline_shovel", [(10, 2), (14, 2), (14, 6), (11, 7), (9, 5)])
    tool("tourmaline_hoe", [(6, 3), (13, 2), (13, 5), (9, 5)])

    def armor(name, shape):
        im = blank(); d = ImageDraw.Draw(im)
        d.polygon(shape, fill=TOUR[0], outline=hexc("8f2449"))
        save(im, f"item/{name}.png")
    armor("tourmaline_helmet", [(3, 4), (13, 4), (13, 10), (11, 10), (11, 7), (5, 7), (5, 10), (3, 10)])
    armor("tourmaline_chestplate", [(2, 2), (6, 2), (8, 4), (10, 2), (14, 2), (14, 6), (12, 6), (12, 14), (4, 14), (4, 6), (2, 6)])
    armor("tourmaline_leggings", [(3, 2), (13, 2), (13, 14), (9, 14), (9, 7), (7, 7), (7, 14), (3, 14)])
    armor("tourmaline_boots", [(2, 7), (6, 7), (6, 12), (7, 13), (2, 13)])
    im = Image.open(os.path.join(T, "item/tourmaline_boots.png")); d = ImageDraw.Draw(im)
    d.polygon([(9, 7), (13, 7), (14, 13), (9, 13)], fill=TOUR[0], outline=hexc("8f2449"))
    save(im, "item/tourmaline_boots.png")

    def egg(name, base, spots):
        im = blank(); d = ImageDraw.Draw(im)
        d.ellipse([3, 1, 12, 14], fill=base, outline=shade(base, 0.6))
        for (x, y) in [(5, 4), (9, 6), (6, 9), (10, 11), (7, 12)]:
            d.rectangle([x, y, x + 1, y + 1], fill=spots)
        save(im, f"item/{name}_spawn_egg.png")
    egg("candy_tube_dog", hexc("ffd1e8"), STRIPE)
    egg("lollipop_guy", hexc("ff4f7b"), hexc("fff2f6"))
    egg("grape_spider", hexc("7b3fa0"), hexc("5fbf4f"))

# ------------------------------------------------------------------ entities
def box(img, u, v, w, h, d, side, top=None, front=None, bottom=None):
    """Paints a model cube's UV net. side/top/front/bottom are callables (x, y, face_w, face_h) -> color or a color."""
    px = img.load()
    def fill(x0, y0, fw, fh, col):
        for y in range(fh):
            for x in range(fw):
                c = col(x, y, fw, fh) if callable(col) else col
                if c is not None and 0 <= x0 + x < img.width and 0 <= y0 + y < img.height:
                    px[x0 + x, y0 + y] = c
    top = top or side; front = front or side; bottom = bottom or side
    fill(u + d, v, w, d, top)
    fill(u + d + w, v, w, d, bottom)
    fill(u, v + d, d, h, side)
    fill(u + d, v + d, w, h, front)
    fill(u + d + w, v + d, d, h, side)
    fill(u + 2 * d + w, v + d, w, h, side)

def entities():
    pink = hexc("ff8fbf"); white = hexc("fff4f8"); dark = hexc("2b1b22")
    def stripes(x, y, w, h):
        return STRIPE if ((x + y) // 2) % 2 == 0 else white
    dog = Image.new("RGBA", (64, 32), (0, 0, 0, 0))
    box(dog, 0, 0, 6, 6, 12, stripes)
    def face(x, y, w, h):
        if y == 2 and x in (1, 4):
            return dark
        if y == 2 and x in (0, 5):
            return white
        return pink
    box(dog, 0, 18, 6, 6, 4, pink, front=face)
    def snout(x, y, w, h):
        return dark if (y == 0 and x == 1) else white
    box(dog, 20, 18, 3, 3, 3, white, front=snout)
    box(dog, 36, 0, 2, 2, 1, hexc("d9487a"))
    box(dog, 36, 18, 2, 6, 2, white, bottom=hexc("d9487a"))
    box(dog, 44, 18, 2, 2, 6, stripes)
    save(dog, "entity/candy_tube_dog.png")

    lg = Image.new("RGBA", (64, 32), (0, 0, 0, 0))
    red = hexc("ff4f7b")
    def swirl(x, y, w, h):
        cx, cy = (w - 1) / 2, (h - 1) / 2
        a = math.atan2(y - cy, x - cx)
        r = math.hypot(x - cx, y - cy)
        return white if int((a / math.tau * 4 + r / 2.2)) % 2 == 0 else red
    def lg_face(x, y, w, h):
        if y == 4 and x in (3, 6):
            return dark
        if y == 6 and 3 <= x <= 6:
            return dark if x in (3, 6) or y == 7 else hexc("8a1c3a")
        return swirl(x, y, w, h)
    box(lg, 0, 0, 10, 10, 2, red, front=lg_face, top=hexc("e8456f"))
    # back face of the disc keeps the swirl
    px = lg.load()
    for y in range(10):
        for x in range(10):
            px[2 + 2 + 10 + x, 2 + y] = swirl(x, y, 10, 10)
    box(lg, 0, 12, 4, 10, 3, white)
    box(lg, 16, 12, 2, 8, 2, hexc("f5e6ee"), bottom=hexc("ffc0df"))
    box(lg, 24, 12, 2, 6, 2, hexc("f5e6ee"), bottom=hexc("c75a86"))
    save(lg, "entity/lollipop_guy.png")

    gs = Image.new("RGBA", (64, 32), (0, 0, 0, 0))
    def gs_face(x, y, w, h):
        if y == 2 and x in (1, 4):
            return hexc("ff3030")
        if y == 3 and x in (2, 3):
            return hexc("ff6060")
        return hexc("4f7f2a")
    box(gs, 0, 0, 6, 6, 5, hexc("4f7f2a"), front=gs_face, top=hexc("6b8e23"))
    def grapes(x, y, w, h):
        cx, cy = (x % 3), (y % 3)
        if cx == 1 and cy == 1:
            return hexc("b07ad1")
        if cx == 2 or cy == 2:
            return hexc("4b2263")
        return hexc("7b3fa0")
    box(gs, 0, 12, 8, 7, 9, grapes)
    box(gs, 36, 0, 12, 2, 2, hexc("3d5c1f"), top=hexc("557a2c"))
    save(gs, "entity/grape_spider.png")

    # Armor layers (vanilla humanoid UV layout, 64x32).
    def armor_layer(parts):
        im = Image.new("RGBA", (64, 32), (0, 0, 0, 0))
        def gem(x, y, w, h):
            if x == 0 or y == 0 or x == w - 1 or y == h - 1:
                return hexc("8f2449")
            return TOUR[(x * 3 + y * 5) % 3]
        for (u, v, w, h, d) in parts:
            box(im, u, v, w, h, d, gem)
        return im
    save(armor_layer([(0, 0, 8, 8, 8), (16, 16, 8, 12, 4), (40, 16, 4, 12, 4), (0, 16, 4, 12, 4)]),
         "entity/equipment/humanoid/tourmaline.png")
    save(armor_layer([(16, 16, 8, 12, 4), (0, 16, 4, 12, 4)]), "entity/equipment/humanoid_leggings/tourmaline.png")

# ------------------------------------------------------------------ gui
def gui():
    im = Image.new("RGBA", (256, 256), (0, 0, 0, 0))
    d = ImageDraw.Draw(im)
    W, H = 176, 166
    bg, light, darkc, black = hexc("c6c6c6"), hexc("ffffff"), hexc("555555"), hexc("000000")
    d.rectangle([0, 0, W - 1, H - 1], fill=bg)
    d.line([(0, 0), (W - 2, 0)], fill=black); d.line([(0, 0), (0, H - 2)], fill=black)
    d.line([(W - 1, 1), (W - 1, H - 1)], fill=black); d.line([(1, H - 1), (W - 1, H - 1)], fill=black)
    d.line([(1, 1), (W - 3, 1)], fill=light); d.line([(1, 1), (1, H - 3)], fill=light)
    d.line([(W - 2, 2), (W - 2, H - 2)], fill=darkc); d.line([(2, H - 2), (W - 2, H - 2)], fill=darkc)

    def slot(x, y, size=18):
        d.rectangle([x, y, x + size - 1, y + size - 1], fill=hexc("8b8b8b"))
        d.line([(x, y), (x + size - 2, y)], fill=hexc("373737")); d.line([(x, y), (x, y + size - 2)], fill=hexc("373737"))
        d.line([(x + 1, y + size - 1), (x + size - 1, y + size - 1)], fill=light); d.line([(x + size - 1, y + 1), (x + size - 1, y + size - 1)], fill=light)
    slot(37, 16); slot(59, 16); slot(48, 52)
    slot(115, 30, 26)
    for r in range(3):
        for c in range(9):
            slot(7 + c * 18, 83 + r * 18)
    for c in range(9):
        slot(7 + c * 18, 141)
    # flame frame (14x14 at 50,37) and arrow outline (24x16 at 85,35)
    d.rectangle([49, 36, 64, 51], outline=hexc("8b8b8b"))
    d.polygon([(85, 39), (101, 39), (101, 35), (108, 43), (101, 50), (101, 46), (85, 46)], fill=hexc("8b8b8b"))
    # chocolate drip decoration along the top edge
    for x in range(3, W - 3):
        h = 2 + (1 if (x * 7) % 11 < 3 else 0)
        for y in range(2, 2 + h):
            im.putpixel((x, y), CHOC[1] if y < 2 + h - 1 else CHOC[0])
    # help "?" box at 158,5
    d.rectangle([158, 5, 169, 16], fill=hexc("8b8b8b"), outline=hexc("373737"))
    for (x, y) in [(162, 7), (163, 7), (164, 7), (165, 8), (165, 9), (164, 10), (163, 11), (163, 12), (163, 14)]:
        im.putpixel((x, y), light)
    save(im, "gui/container/chocolate_factory.png")

if __name__ == "__main__":
    blocks(); items(); entities(); gui()
    import gen_textures_v2  # tools/gen_textures_v2.py: stage 2 textures (replaces some stage 1 art)
    gen_textures_v2.main()
    import gen_mobs_v3  # tools/gen_mobs_v3.py: stage 3 creature textures (UV layout read from the Java models)
    gen_mobs_v3.main()
    print("textures generated")
