# -*- coding: utf-8 -*-
"""Stage 6 translations (Ice Cream Dimension, portal, amulet, ice cream creatures, Ice Cream Nest and Dragon)."""
from lang_data import _common, N, I, B

EN = _common(
    {
        B("vanilla_ice_cream_block"): "Vanilla Ice Cream Block", B("chocolate_ice_cream_block"): "Chocolate Ice Cream Block",
        B("strawberry_ice_cream_block"): "Strawberry Ice Cream Block", B("mint_ice_cream_block"): "Mint Ice Cream Block",
        B("ice_cream_portal"): "Ice Cream Portal", B("ice_cream_dragon_egg"): "Ice Cream Dragon Egg",
        I("mint_ice_cream"): "Mint Ice Cream", I("ultimate_ice_cream"): "Ultimate Ice Cream", I("ice_cream_amulet"): "Ice Cream Amulet",
        I("ice_cream_zombie_spawn_egg"): "Ice Cream Zombie Spawn Egg", I("living_ice_cream_spawn_egg"): "Living Ice Cream Spawn Egg",
        I("ice_cream_beast_spawn_egg"): "Ice Cream Beast Spawn Egg", I("ice_cream_gargoyle_spawn_egg"): "Ice Cream Gargoyle Spawn Egg",
        I("angry_ice_cream_cone_spawn_egg"): "Angry Ice Cream Cone Spawn Egg", I("ice_cream_dragon_spawn_egg"): "Ice Cream Dragon Spawn Egg",
    },
    {
        B("chocolate_ice_cream_block") + ".desc": "Build a 4x5 frame and light it with the Ice Cream Amulet.",
        B("ice_cream_dragon_egg") + ".desc": "Right-click it to wake the Ice Cream Dragon.",
        I("mint_ice_cream") + ".desc": "Refreshing. Gives Speed.",
        I("ultimate_ice_cream") + ".desc": "Four flavours at once. Many effects.",
        I("ice_cream_amulet") + ".desc": "Use on the inside of a Chocolate Ice Cream Block frame.",
        I("ice_cream_amulet") + ".desc.2": "Opens a portal to the Ice Cream Dimension.",
        I("ice_cream_zombie_spawn_egg") + ".desc": "Hostile. Comes in chocolate, vanilla, strawberry or mint.",
        I("ice_cream_beast_spawn_egg") + ".desc": "Hostile. Keeps buffing itself in a fight.",
        I("ice_cream_gargoyle_spawn_egg") + ".desc": "Hostile. Flies and dives at you.",
        I("living_ice_cream_spawn_egg") + ".desc": "Use a Wafer Cone on it to scoop it... at your own risk.",
        I("ice_cream_dragon_spawn_egg") + ".desc": "Boss. Fireballs, roars and summons cones.",
    },
    {
        "ice_cream_zombie": "Ice Cream Zombie", "living_ice_cream": "Living Ice Cream",
        "ice_cream_zombie.chocolate": "Chocolate Ice Cream Zombie", "living_ice_cream.chocolate": "Living Chocolate Ice Cream",
        "ice_cream_zombie.vanilla": "Vanilla Ice Cream Zombie", "living_ice_cream.vanilla": "Living Vanilla Ice Cream",
        "ice_cream_zombie.strawberry": "Strawberry Ice Cream Zombie", "living_ice_cream.strawberry": "Living Strawberry Ice Cream",
        "ice_cream_zombie.mint": "Mint Ice Cream Zombie", "living_ice_cream.mint": "Living Mint Ice Cream",
        "ice_cream_beast": "Ice Cream Beast", "ice_cream_gargoyle": "Ice Cream Gargoyle",
        "angry_ice_cream_cone": "Angry Ice Cream Cone", "ice_cream_dragon": "Ice Cream Dragon",
    },
    {
        "ice_cream_zombie.ambient": "Ice Cream Zombie groans", "ice_cream_zombie.hurt": "Ice Cream Zombie hurts",
        "ice_cream_zombie.death": "Ice Cream Zombie melts",
        "ice_cream_beast.ambient": "Ice Cream Beast grunts", "ice_cream_beast.hurt": "Ice Cream Beast hurts",
        "ice_cream_beast.death": "Ice Cream Beast collapses",
        "ice_cream_gargoyle.ambient": "Ice Cream Gargoyle screeches", "ice_cream_gargoyle.hurt": "Ice Cream Gargoyle hurts",
        "ice_cream_gargoyle.death": "Ice Cream Gargoyle dies",
        "living_ice_cream.ambient": "Living Ice Cream squishes", "living_ice_cream.hurt": "Living Ice Cream hurts",
        "living_ice_cream.death": "Living Ice Cream melts",
        "angry_ice_cream_cone.ambient": "Angry Cone grumbles", "angry_ice_cream_cone.hurt": "Angry Cone hurts",
        "angry_ice_cream_cone.death": "Angry Cone crumbles",
        "ice_cream_dragon.ambient": "Ice Cream Dragon growls", "ice_cream_dragon.hurt": "Ice Cream Dragon hurts",
        "ice_cream_dragon.death": "Ice Cream Dragon dies", "ice_cream_dragon.roar": "Ice Cream Dragon roars",
    },
    {
        "ultimate_ice_cream": ("Four Scoops of Joy", "Make an Ultimate Ice Cream"),
        "ice_cream_amulet": ("Key to the Freezer", "Buy the Ice Cream Amulet from a master Ice Cream Vendor"),
        "enter_ice_cream_dimension": ("Brain Freeze Dimension", "Travel to the Ice Cream Dimension"),
        "scoop_thief": ("Cone Rage", "Defeat an Angry Ice Cream Cone"),
        "visit_ice_cream_nest": ("Something Is Hatching", "Find an Ice Cream Nest"),
        "dragon_killer": ("Dragon Killer", "Defeat the Ice Cream Dragon"),
    },
    {
        f"biome.{N}.ice_cream_plains": "Ice Cream Plains",
        f"gui.{N}.ice_cream_machine.help.3": "Flavours: Sugar, Sweet Berries, Cocoa Powder, Fern.",
    },
    {
        "iceCreamPortalEnabled": "Ice Cream Portals", "iceCreamNestFrequency": "Ice Cream Nest Frequency",
        "iceCreamPinnacles": "Ice Cream Pinnacles", "iceCreamZombieSpawnChance": "Ice Cream Zombie Spawn Chance",
        "iceCreamBeastSpawnChance": "Ice Cream Beast Spawn Chance", "iceCreamGargoyleSpawnChance": "Ice Cream Gargoyle Spawn Chance",
        "livingIceCreamSpawnChance": "Living Ice Cream Spawn Chance", "angryIceCreamConeSpawnChance": "Angry Ice Cream Cone Spawn Chance",
        "iceCreamBeastBuffs": "Ice Cream Beast Buffs", "iceCreamDragonHealth": "Ice Cream Dragon Health",
        "iceCreamDragonFireballPower": "Ice Cream Dragon Fireball Power", "iceCreamDragonMaxCones": "Ice Cream Dragon Max Cones",
    },
    {},
)

PT = _common(
    {
        B("vanilla_ice_cream_block"): "Bloco de Sorvete de Baunilha", B("chocolate_ice_cream_block"): "Bloco de Sorvete de Chocolate",
        B("strawberry_ice_cream_block"): "Bloco de Sorvete de Morango", B("mint_ice_cream_block"): "Bloco de Sorvete de Menta",
        B("ice_cream_portal"): "Portal de Sorvete", B("ice_cream_dragon_egg"): "Ovo do Dragão de Sorvete",
        I("mint_ice_cream"): "Sorvete de Menta", I("ultimate_ice_cream"): "Sorvete Supremo", I("ice_cream_amulet"): "Amuleto de Sorvete",
        I("ice_cream_zombie_spawn_egg"): "Ovo Gerador de Zumbi de Sorvete", I("living_ice_cream_spawn_egg"): "Ovo Gerador de Sorvete Vivo",
        I("ice_cream_beast_spawn_egg"): "Ovo Gerador de Fera de Sorvete", I("ice_cream_gargoyle_spawn_egg"): "Ovo Gerador de Gárgula de Sorvete",
        I("angry_ice_cream_cone_spawn_egg"): "Ovo Gerador de Casquinha Raivosa", I("ice_cream_dragon_spawn_egg"): "Ovo Gerador de Dragão de Sorvete",
    },
    {
        B("chocolate_ice_cream_block") + ".desc": "Monte uma moldura 4x5 e acenda com o Amuleto de Sorvete.",
        B("ice_cream_dragon_egg") + ".desc": "Clique com o botão direito para acordar o Dragão de Sorvete.",
        I("mint_ice_cream") + ".desc": "Refrescante. Dá Velocidade.",
        I("ultimate_ice_cream") + ".desc": "Quatro sabores de uma vez. Muitos efeitos.",
        I("ice_cream_amulet") + ".desc": "Use no lado de dentro de uma moldura de Blocos de Sorvete de Chocolate.",
        I("ice_cream_amulet") + ".desc.2": "Abre um portal para a Dimensão do Sorvete.",
        I("ice_cream_zombie_spawn_egg") + ".desc": "Hostil. Vem em chocolate, baunilha, morango ou menta.",
        I("ice_cream_beast_spawn_egg") + ".desc": "Hostil. Fica se fortalecendo durante a luta.",
        I("ice_cream_gargoyle_spawn_egg") + ".desc": "Hostil. Voa e mergulha em você.",
        I("living_ice_cream_spawn_egg") + ".desc": "Use uma Casquinha nele para pegar o sorvete... por sua conta e risco.",
        I("ice_cream_dragon_spawn_egg") + ".desc": "Chefe. Bolas de fogo, rugidos e invoca casquinhas.",
    },
    {
        "ice_cream_zombie": "Zumbi de Sorvete", "living_ice_cream": "Sorvete Vivo",
        "ice_cream_zombie.chocolate": "Zumbi de Sorvete de Chocolate", "living_ice_cream.chocolate": "Sorvete Vivo de Chocolate",
        "ice_cream_zombie.vanilla": "Zumbi de Sorvete de Baunilha", "living_ice_cream.vanilla": "Sorvete Vivo de Baunilha",
        "ice_cream_zombie.strawberry": "Zumbi de Sorvete de Morango", "living_ice_cream.strawberry": "Sorvete Vivo de Morango",
        "ice_cream_zombie.mint": "Zumbi de Sorvete de Menta", "living_ice_cream.mint": "Sorvete Vivo de Menta",
        "ice_cream_beast": "Fera de Sorvete", "ice_cream_gargoyle": "Gárgula de Sorvete",
        "angry_ice_cream_cone": "Casquinha Raivosa", "ice_cream_dragon": "Dragão de Sorvete",
    },
    {
        "ice_cream_zombie.ambient": "Zumbi de Sorvete geme", "ice_cream_zombie.hurt": "Zumbi de Sorvete se machuca",
        "ice_cream_zombie.death": "Zumbi de Sorvete derrete",
        "ice_cream_beast.ambient": "Fera de Sorvete grunhe", "ice_cream_beast.hurt": "Fera de Sorvete se machuca",
        "ice_cream_beast.death": "Fera de Sorvete desaba",
        "ice_cream_gargoyle.ambient": "Gárgula de Sorvete guincha", "ice_cream_gargoyle.hurt": "Gárgula de Sorvete se machuca",
        "ice_cream_gargoyle.death": "Gárgula de Sorvete morre",
        "living_ice_cream.ambient": "Sorvete Vivo faz squish", "living_ice_cream.hurt": "Sorvete Vivo se machuca",
        "living_ice_cream.death": "Sorvete Vivo derrete",
        "angry_ice_cream_cone.ambient": "Casquinha Raivosa resmunga", "angry_ice_cream_cone.hurt": "Casquinha Raivosa se machuca",
        "angry_ice_cream_cone.death": "Casquinha Raivosa esfarela",
        "ice_cream_dragon.ambient": "Dragão de Sorvete rosna", "ice_cream_dragon.hurt": "Dragão de Sorvete se machuca",
        "ice_cream_dragon.death": "Dragão de Sorvete morre", "ice_cream_dragon.roar": "Dragão de Sorvete ruge",
    },
    {
        "ultimate_ice_cream": ("Quatro Bolas de Alegria", "Faça um Sorvete Supremo"),
        "ice_cream_amulet": ("Chave do Freezer", "Compre o Amuleto de Sorvete de um Sorveteiro mestre"),
        "enter_ice_cream_dimension": ("Dimensão do Cérebro Congelado", "Viaje para a Dimensão do Sorvete"),
        "scoop_thief": ("Casquinha Furiosa", "Derrote uma Casquinha Raivosa"),
        "visit_ice_cream_nest": ("Algo Está Chocando", "Encontre um Ninho de Sorvete"),
        "dragon_killer": ("Matador de Dragão", "Derrote o Dragão de Sorvete"),
    },
    {
        f"biome.{N}.ice_cream_plains": "Planícies de Sorvete",
        f"gui.{N}.ice_cream_machine.help.3": "Sabores: Açúcar, Frutas Doces, Cacau em Pó, Samambaia.",
    },
    {
        "iceCreamPortalEnabled": "Portais de Sorvete", "iceCreamNestFrequency": "Frequência de Ninhos de Sorvete",
        "iceCreamPinnacles": "Pináculos de Sorvete", "iceCreamZombieSpawnChance": "Chance de Zumbis de Sorvete",
        "iceCreamBeastSpawnChance": "Chance de Feras de Sorvete", "iceCreamGargoyleSpawnChance": "Chance de Gárgulas de Sorvete",
        "livingIceCreamSpawnChance": "Chance de Sorvetes Vivos", "angryIceCreamConeSpawnChance": "Chance de Casquinhas Raivosas",
        "iceCreamBeastBuffs": "Efeitos da Fera de Sorvete", "iceCreamDragonHealth": "Vida do Dragão de Sorvete",
        "iceCreamDragonFireballPower": "Força das Bolas de Fogo do Dragão", "iceCreamDragonMaxCones": "Máximo de Casquinhas do Dragão",
    },
    {},
)
