# -*- coding: utf-8 -*-
"""Stage 2 translations (Sweet Forest rework, Jelly Bean Fields). Merged over lang_data.py; same keys replace stage 1 names."""
from lang_data import _common, N, B, I

REMOVED = [f"{N}.configuration.sweetForestRegionWeight", f"{N}.configuration.grapeSpiderSpawnChance"]

def _extra(fluids):
    d = {}
    for k, v in fluids.items():
        d[f"block.{N}.{k}"] = v
        d[f"fluid_type.{N}.{k}"] = v
    return d

EN = _common(
    {
        # Renamed to match the original mod (ids unchanged so stage 1 worlds keep their blocks).
        B("chocolate_grass_block"): "Gummy Grass", B("chocolate_soil"): "Chocolate Dirt",
        B("sweetwood_log"): "Candy Log", B("sweetwood_planks"): "Candy Planks", B("cotton_candy_leaves"): "Candy Leaves",
        B("sweetwood_sapling"): "Candy Sapling",
        B("sweetwood_stairs"): "Candy Stairs", B("sweetwood_slab"): "Candy Slab", B("sweetwood_fence"): "Candy Fence",
        B("sweetwood_fence_gate"): "Candy Fence Gate", B("sweetwood_door"): "Candy Door", B("sweetwood_button"): "Candy Button",
        B("sweetwood_pressure_plate"): "Candy Pressure Plate",
        B("gingerbread_block"): "Gingerbread Block", B("frosted_gingerbread_block"): "Frosted Gingerbread Block",
        B("gingerbread_stairs"): "Gingerbread Stairs", B("gingerbread_slab"): "Gingerbread Slab",
        B("red_licorice_plant"): "Red Licorice Plant",
        B("green_jelly_bean_block"): "Green Jelly Bean Block", B("yellow_jelly_bean_block"): "Yellow Jelly Bean Block",
        B("red_jelly_bean_block"): "Red Jelly Bean Block", B("orange_jelly_bean_block"): "Orange Jelly Bean Block",
        B("purple_jelly_bean_block"): "Purple Jelly Bean Block", B("infested_purple_jelly_bean_block"): "Infested Purple Jelly Bean Block",
        I("red_licorice"): "Red Licorice", I("cooked_licorice"): "Cooked Licorice", I("gingerbread"): "Gingerbread",
        I("gumdrop"): "Gumdrop", I("roll_cake"): "Roll Cake", I("jelly_beans"): "Jelly Beans",
        I("brown_sugar_brick"): "Brown Sugar Brick", I("brown_sugar_sword"): "Brown Sugar Sword",
        I("dead_jelly_snake"): "Dead Jelly Snake", I("jelly_bazooka"): "Jelly Bazooka", I("heavy_boots"): "Heavy Boots",
        I("melted_chocolate_bucket"): "Melted Chocolate Bucket", I("bubbaloo_bucket"): "Bubbaloo Bucket",
        I("brown_sugar_rhino_spawn_egg"): "Brown Sugar Rhino Spawn Egg", I("cotton_candy_tornado_spawn_egg"): "Cotton Candy Tornado Spawn Egg",
        I("bubblegum_spawn_egg"): "Bubblegum Spawn Egg", I("gingerbread_warrior_spawn_egg"): "Gingerbread Warrior Spawn Egg",
        I("gingerbread_soldier_spawn_egg"): "Gingerbread Soldier Spawn Egg", I("jelly_bunny_spawn_egg"): "Jelly Bunny Spawn Egg",
        I("jelly_snake_spawn_egg"): "Jelly Snake Spawn Egg", I("jelly_shark_spawn_egg"): "Jelly Shark Spawn Egg",
        I("roll_cake_monster_spawn_egg"): "Roll Cake Monster Spawn Egg", I("bubbaloo_creeper_spawn_egg"): "Bubbaloo Creeper Spawn Egg",
    },
    {
        B("chocolate_grass_block") + ".desc": "The pink, gummy ground of the Sweet Forest.",
        B("sweetwood_sapling") + ".desc": "Grows a Candy Tree with Candy Leaves.",
        B("red_licorice_plant") + ".desc": "Grows on Gummy Grass. Break it for Red Licorice.",
        B("frosted_gingerbread_block") + ".desc": "Gingerbread Block with a coat of icing.",
        B("green_jelly_bean_block") + ".desc": "Bouncy. Landing on jelly halves fall damage.",
        B("yellow_jelly_bean_block") + ".desc": "Bouncy. Walking on it slows your mining (Mining Fatigue).",
        B("red_jelly_bean_block") + ".desc": "Bouncy. Punching it makes you hungry.",
        B("orange_jelly_bean_block") + ".desc": "Bouncy. Explodes a second after you step on it. Sneak to cross safely.",
        B("purple_jelly_bean_block") + ".desc": "Bouncy. Some purple jelly hides Grape Spiders.",
        B("infested_purple_jelly_bean_block") + ".desc": "Releases Grape Spiders when broken.",
        I("red_licorice") + ".desc": "Chewy. Better cooked.",
        I("brown_sugar_brick") + ".desc": "Throw it! Dropped by Brown Sugar Rhinos.",
        I("brown_sugar_sword") + ".desc": "Hits knock enemies far back.",
        I("jelly_bazooka") + ".desc": "Fires Dead Jelly Snakes. Needs them in your inventory.",
        I("heavy_boots") + ".desc": "Stops jelly blocks from bouncing you.",
        I("melted_chocolate_bucket") + ".desc": "The Chocolate Factory turns it into 10 Chocolate Bars.",
        I("bubbaloo_bucket") + ".desc": "Hot, sticky gum. Hurts whoever wades in.",
        I("dead_jelly_snake") + ".desc": "Jelly Bazooka ammo.",
        I("brown_sugar_rhino_spawn_egg") + ".desc": "Neutral. Charges when hit.",
        I("cotton_candy_tornado_spawn_egg") + ".desc": "Hostile. When weak, catch it with a Stick for Cotton Candy.",
        I("bubblegum_spawn_egg") + ".desc": "Hostile and flying. Pops when it dies.",
        I("gingerbread_warrior_spawn_egg") + ".desc": "Hostile. Guards Gingerbread Towers.",
        I("gingerbread_soldier_spawn_egg") + ".desc": "Hostile. Shoots gumdrops.",
        I("jelly_bunny_spawn_egg") + ".desc": "Passive. Breed with Jelly Beans.",
        I("jelly_snake_spawn_egg") + ".desc": "Hostile. Its bite poisons.",
        I("jelly_shark_spawn_egg") + ".desc": "Hostile. Hunts swimmers in the Jelly Bean Fields.",
        I("roll_cake_monster_spawn_egg") + ".desc": "Neutral. Hits hard when angered.",
        I("bubbaloo_creeper_spawn_egg") + ".desc": "Hostile. Leaves a pool of Bubbaloo when it dies.",
    },
    {"brown_sugar_rhino": "Brown Sugar Rhino", "cotton_candy_tornado": "Cotton Candy Tornado", "bubblegum": "Bubblegum",
     "gingerbread_warrior": "Gingerbread Warrior", "gingerbread_soldier": "Gingerbread Soldier", "jelly_bunny": "Jelly Bunny",
     "jelly_snake": "Jelly Snake", "jelly_shark": "Jelly Shark", "roll_cake_monster": "Roll Cake Monster",
     "bubbaloo_creeper": "Bubbaloo Creeper", "brown_sugar_brick": "Brown Sugar Brick", "gumdrop_shot": "Gumdrop",
     "jelly_snake_shot": "Jelly Snake Shot"},
    {
        "brown_sugar_rhino.ambient": "Rhino snorts", "brown_sugar_rhino.hurt": "Rhino hurts", "brown_sugar_rhino.death": "Rhino dies",
        "cotton_candy_tornado.ambient": "Tornado whirls", "cotton_candy_tornado.hurt": "Tornado hurts", "cotton_candy_tornado.death": "Tornado fades",
        "bubblegum.ambient": "Bubblegum squelches", "bubblegum.hurt": "Bubblegum hurts", "bubblegum.death": "Bubblegum dies",
        "bubblegum.pop": "Bubblegum pops",
        "gingerbread.ambient": "Gingerbread creaks", "gingerbread.hurt": "Gingerbread cracks", "gingerbread.death": "Gingerbread crumbles",
        "gingerbread_soldier.shoot": "Gumdrop fired",
        "jelly_bunny.ambient": "Jelly Bunny squeaks", "jelly_bunny.hurt": "Jelly Bunny hurts", "jelly_bunny.death": "Jelly Bunny dies",
        "jelly_snake.ambient": "Jelly Snake hisses", "jelly_snake.hurt": "Jelly Snake hurts", "jelly_snake.death": "Jelly Snake dies",
        "jelly_shark.ambient": "Jelly Shark gurgles", "jelly_shark.hurt": "Jelly Shark hurts", "jelly_shark.death": "Jelly Shark dies",
        "roll_cake_monster.ambient": "Roll Cake rumbles", "roll_cake_monster.hurt": "Roll Cake hurts", "roll_cake_monster.death": "Roll Cake dies",
    },
    {
        "root": ("Crazy Alloy: Revival", "Sweet worlds, strange creatures. Candy biomes replace some forests and plains."),
        "enter_sweet_forest": ("A Sweet Discovery", "Enter a Sweet Forest"),
        "ouch": ("Ouch!", "Hit a creature with a thrown Brown Sugar Brick"),
        "cotton_candy_catch": ("Catch the Wind", "Catch a weakened Cotton Candy Tornado with a Stick"),
        "licorice_harvest": ("Chewy", "Harvest Red Licorice"),
        "chocolate_river": ("Chocolate River", "Fill a bucket with Melted Chocolate"),
        "visit_gingerbread_tower": ("Tower of Spice", "Find a Gingerbread Tower in a Sweet Forest"),
        "enter_jelly_bean_fields": ("Bean There", "Enter the Jelly Bean Fields"),
        "boing": ("Boing!", "Hit a creature with the Jelly Bazooka"),
        "heavy_boots": ("Feet on the Ground", "Get Heavy Boots"),
    },
    _extra({"melted_chocolate": "Melted Chocolate", "bubbaloo": "Bubbaloo"}) | {
        f"biome.{N}.jelly_bean_fields": "Jelly Bean Fields",
        f"death.attack.{N}.bubbaloo": "%1$s got stuck in Bubbaloo",
        f"death.attack.{N}.bubbaloo.player": "%1$s got stuck in Bubbaloo while fighting %2$s",
    },
    {
        "candyRegionWeight": "Candy Biome Frequency", "sweetForestEnabled": "Generate Sweet Forest",
        "jellyBeanFieldsEnabled": "Generate Jelly Bean Fields", "gingerbreadTowerFrequency": "Gingerbread Tower Frequency",
        "brownSugarRhinoSpawnChance": "Brown Sugar Rhino Spawn Chance", "cottonCandyTornadoSpawnChance": "Cotton Candy Tornado Spawn Chance",
        "bubblegumSpawnChance": "Bubblegum Spawn Chance", "jellyBunnySpawnChance": "Jelly Bunny Spawn Chance",
        "jellySnakeSpawnChance": "Jelly Snake Spawn Chance", "jellySharkSpawnChance": "Jelly Shark Spawn Chance",
        "rollCakeMonsterSpawnChance": "Roll Cake Monster Spawn Chance", "bubbalooCreeperSpawnChance": "Bubbaloo Creeper Spawn Chance",
        "jellySnakePoisonSeconds": "Jelly Snake Poison (seconds)", "bubblegumExplosionPower": "Bubblegum Pop Power",
        "orangeJellyExplosionPower": "Orange Jelly Explosion Power",
    },
    {},
)

PT = _common(
    {
        B("chocolate_grass_block"): "Grama de Goma", B("chocolate_soil"): "Terra de Chocolate",
        B("sweetwood_log"): "Tronco de Doce", B("sweetwood_planks"): "Tábuas de Doce", B("cotton_candy_leaves"): "Folhas de Doce",
        B("sweetwood_sapling"): "Muda de Doce",
        B("sweetwood_stairs"): "Escada de Doce", B("sweetwood_slab"): "Laje de Doce", B("sweetwood_fence"): "Cerca de Doce",
        B("sweetwood_fence_gate"): "Portão de Doce", B("sweetwood_door"): "Porta de Doce", B("sweetwood_button"): "Botão de Doce",
        B("sweetwood_pressure_plate"): "Placa de Pressão de Doce",
        B("gingerbread_block"): "Bloco de Pão de Mel", B("frosted_gingerbread_block"): "Bloco de Pão de Mel Glaceado",
        B("gingerbread_stairs"): "Escada de Pão de Mel", B("gingerbread_slab"): "Laje de Pão de Mel",
        B("red_licorice_plant"): "Planta de Alcaçuz Vermelho",
        B("green_jelly_bean_block"): "Bloco de Jujuba Verde", B("yellow_jelly_bean_block"): "Bloco de Jujuba Amarela",
        B("red_jelly_bean_block"): "Bloco de Jujuba Vermelha", B("orange_jelly_bean_block"): "Bloco de Jujuba Laranja",
        B("purple_jelly_bean_block"): "Bloco de Jujuba Roxa", B("infested_purple_jelly_bean_block"): "Bloco de Jujuba Roxa Infestado",
        I("red_licorice"): "Alcaçuz Vermelho", I("cooked_licorice"): "Alcaçuz Assado", I("gingerbread"): "Pão de Mel",
        I("gumdrop"): "Bala de Goma", I("roll_cake"): "Rocambole", I("jelly_beans"): "Jujubas",
        I("brown_sugar_brick"): "Tijolo de Açúcar Mascavo", I("brown_sugar_sword"): "Espada de Açúcar Mascavo",
        I("dead_jelly_snake"): "Cobra de Gelatina Morta", I("jelly_bazooka"): "Bazuca de Gelatina", I("heavy_boots"): "Botas Pesadas",
        I("melted_chocolate_bucket"): "Balde de Chocolate Derretido", I("bubbaloo_bucket"): "Balde de Bubbaloo",
        I("brown_sugar_rhino_spawn_egg"): "Ovo Gerador de Rinoceronte de Açúcar Mascavo",
        I("cotton_candy_tornado_spawn_egg"): "Ovo Gerador de Tornado de Algodão-Doce",
        I("bubblegum_spawn_egg"): "Ovo Gerador de Chiclete", I("gingerbread_warrior_spawn_egg"): "Ovo Gerador de Guerreiro de Pão de Mel",
        I("gingerbread_soldier_spawn_egg"): "Ovo Gerador de Soldado de Pão de Mel", I("jelly_bunny_spawn_egg"): "Ovo Gerador de Coelho de Gelatina",
        I("jelly_snake_spawn_egg"): "Ovo Gerador de Cobra de Gelatina", I("jelly_shark_spawn_egg"): "Ovo Gerador de Tubarão de Gelatina",
        I("roll_cake_monster_spawn_egg"): "Ovo Gerador de Monstro Rocambole", I("bubbaloo_creeper_spawn_egg"): "Ovo Gerador de Creeper de Bubbaloo",
    },
    {
        B("chocolate_grass_block") + ".desc": "O chão rosa e grudento da Floresta Doce.",
        B("sweetwood_sapling") + ".desc": "Cresce uma Árvore de Doce com Folhas de Doce.",
        B("red_licorice_plant") + ".desc": "Cresce na Grama de Goma. Quebre para pegar Alcaçuz Vermelho.",
        B("frosted_gingerbread_block") + ".desc": "Bloco de Pão de Mel com cobertura de glacê.",
        B("green_jelly_bean_block") + ".desc": "Elástico. Cair em jujuba reduz o dano de queda pela metade.",
        B("yellow_jelly_bean_block") + ".desc": "Elástico. Andar nele deixa sua mineração lenta (Fadiga de Mineração).",
        B("red_jelly_bean_block") + ".desc": "Elástico. Socar dá fome.",
        B("orange_jelly_bean_block") + ".desc": "Elástico. Explode um segundo depois de pisado. Agache para passar com segurança.",
        B("purple_jelly_bean_block") + ".desc": "Elástico. Algumas jujubas roxas escondem Aranhas de Uva.",
        B("infested_purple_jelly_bean_block") + ".desc": "Solta Aranhas de Uva quando quebrado.",
        I("red_licorice") + ".desc": "Borrachudo. Melhor assado.",
        I("brown_sugar_brick") + ".desc": "Arremesse! Dropado pelo Rinoceronte de Açúcar Mascavo.",
        I("brown_sugar_sword") + ".desc": "Os golpes empurram os inimigos para longe.",
        I("jelly_bazooka") + ".desc": "Dispara Cobras de Gelatina Mortas. Precisa delas no inventário.",
        I("heavy_boots") + ".desc": "Impede que os blocos de jujuba façam você quicar.",
        I("melted_chocolate_bucket") + ".desc": "A Fábrica de Chocolate transforma em 10 Barras de Chocolate.",
        I("bubbaloo_bucket") + ".desc": "Chiclete quente e grudento. Machuca quem entra.",
        I("dead_jelly_snake") + ".desc": "Munição da Bazuca de Gelatina.",
        I("brown_sugar_rhino_spawn_egg") + ".desc": "Neutro. Investe quando atacado.",
        I("cotton_candy_tornado_spawn_egg") + ".desc": "Hostil. Quando fraco, capture com um Graveto para ganhar Algodão-Doce.",
        I("bubblegum_spawn_egg") + ".desc": "Hostil e voador. Estoura quando morre.",
        I("gingerbread_warrior_spawn_egg") + ".desc": "Hostil. Guarda as Torres de Pão de Mel.",
        I("gingerbread_soldier_spawn_egg") + ".desc": "Hostil. Atira balas de goma.",
        I("jelly_bunny_spawn_egg") + ".desc": "Passivo. Reproduza com Jujubas.",
        I("jelly_snake_spawn_egg") + ".desc": "Hostil. A mordida envenena.",
        I("jelly_shark_spawn_egg") + ".desc": "Hostil. Caça quem nada nos Campos de Jujuba.",
        I("roll_cake_monster_spawn_egg") + ".desc": "Neutro. Bate forte quando irritado.",
        I("bubbaloo_creeper_spawn_egg") + ".desc": "Hostil. Deixa uma poça de Bubbaloo ao morrer.",
    },
    {"brown_sugar_rhino": "Rinoceronte de Açúcar Mascavo", "cotton_candy_tornado": "Tornado de Algodão-Doce", "bubblegum": "Chiclete",
     "gingerbread_warrior": "Guerreiro de Pão de Mel", "gingerbread_soldier": "Soldado de Pão de Mel", "jelly_bunny": "Coelho de Gelatina",
     "jelly_snake": "Cobra de Gelatina", "jelly_shark": "Tubarão de Gelatina", "roll_cake_monster": "Monstro Rocambole",
     "bubbaloo_creeper": "Creeper de Bubbaloo", "brown_sugar_brick": "Tijolo de Açúcar Mascavo", "gumdrop_shot": "Bala de Goma",
     "jelly_snake_shot": "Tiro de Cobra de Gelatina"},
    {
        "brown_sugar_rhino.ambient": "Rinoceronte bufa", "brown_sugar_rhino.hurt": "Rinoceronte se machuca", "brown_sugar_rhino.death": "Rinoceronte morre",
        "cotton_candy_tornado.ambient": "Tornado gira", "cotton_candy_tornado.hurt": "Tornado se machuca", "cotton_candy_tornado.death": "Tornado se desfaz",
        "bubblegum.ambient": "Chiclete gruda", "bubblegum.hurt": "Chiclete se machuca", "bubblegum.death": "Chiclete morre",
        "bubblegum.pop": "Chiclete estoura",
        "gingerbread.ambient": "Pão de mel range", "gingerbread.hurt": "Pão de mel racha", "gingerbread.death": "Pão de mel esfarela",
        "gingerbread_soldier.shoot": "Bala de goma disparada",
        "jelly_bunny.ambient": "Coelho de Gelatina guincha", "jelly_bunny.hurt": "Coelho de Gelatina se machuca", "jelly_bunny.death": "Coelho de Gelatina morre",
        "jelly_snake.ambient": "Cobra de Gelatina sibila", "jelly_snake.hurt": "Cobra de Gelatina se machuca", "jelly_snake.death": "Cobra de Gelatina morre",
        "jelly_shark.ambient": "Tubarão de Gelatina borbulha", "jelly_shark.hurt": "Tubarão de Gelatina se machuca", "jelly_shark.death": "Tubarão de Gelatina morre",
        "roll_cake_monster.ambient": "Rocambole ronca", "roll_cake_monster.hurt": "Rocambole se machuca", "roll_cake_monster.death": "Rocambole morre",
    },
    {
        "root": ("Crazy Alloy: Revival", "Mundos doces, criaturas estranhas. Biomas de doce substituem algumas florestas e planícies."),
        "enter_sweet_forest": ("Uma Descoberta Doce", "Entre em uma Floresta Doce"),
        "ouch": ("Ai!", "Acerte uma criatura com um Tijolo de Açúcar Mascavo arremessado"),
        "cotton_candy_catch": ("Pegando o Vento", "Capture um Tornado de Algodão-Doce enfraquecido com um Graveto"),
        "licorice_harvest": ("Borrachudo", "Colha Alcaçuz Vermelho"),
        "chocolate_river": ("Rio de Chocolate", "Encha um balde com Chocolate Derretido"),
        "visit_gingerbread_tower": ("Torre de Especiarias", "Encontre uma Torre de Pão de Mel em uma Floresta Doce"),
        "enter_jelly_bean_fields": ("Que Jujuba!", "Entre nos Campos de Jujuba"),
        "boing": ("Boing!", "Acerte uma criatura com a Bazuca de Gelatina"),
        "heavy_boots": ("Pés no Chão", "Consiga Botas Pesadas"),
    },
    _extra({"melted_chocolate": "Chocolate Derretido", "bubbaloo": "Bubbaloo"}) | {
        f"biome.{N}.jelly_bean_fields": "Campos de Jujuba",
        f"death.attack.{N}.bubbaloo": "%1$s ficou grudado no Bubbaloo",
        f"death.attack.{N}.bubbaloo.player": "%1$s ficou grudado no Bubbaloo enquanto lutava contra %2$s",
    },
    {
        "candyRegionWeight": "Frequência dos Biomas de Doce", "sweetForestEnabled": "Gerar Floresta Doce",
        "jellyBeanFieldsEnabled": "Gerar Campos de Jujuba", "gingerbreadTowerFrequency": "Frequência da Torre de Pão de Mel",
        "brownSugarRhinoSpawnChance": "Chance de Rinoceronte de Açúcar Mascavo", "cottonCandyTornadoSpawnChance": "Chance de Tornado de Algodão-Doce",
        "bubblegumSpawnChance": "Chance de Chiclete", "jellyBunnySpawnChance": "Chance de Coelho de Gelatina",
        "jellySnakeSpawnChance": "Chance de Cobra de Gelatina", "jellySharkSpawnChance": "Chance de Tubarão de Gelatina",
        "rollCakeMonsterSpawnChance": "Chance de Monstro Rocambole", "bubbalooCreeperSpawnChance": "Chance de Creeper de Bubbaloo",
        "jellySnakePoisonSeconds": "Veneno da Cobra de Gelatina (segundos)", "bubblegumExplosionPower": "Força do Estouro do Chiclete",
        "orangeJellyExplosionPower": "Força da Explosão da Jujuba Laranja",
    },
    {},
)
